// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8wvBFZYkWt4xsKf_uOmvaK969IUWsb8',
    appId: '1:1081926756389:web:f7fd8a030c800b40d7b7cc',
    messagingSenderId: '1081926756389',
    projectId: 'ecommerce-abe3b',
    authDomain: 'ecommerce-abe3b.firebaseapp.com',
    storageBucket: 'ecommerce-abe3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4J90vzySAHeN5-W3NqTJ1VHDRUzwbuEw',
    appId: '1:1081926756389:android:71a9234a24587ce0d7b7cc',
    messagingSenderId: '1081926756389',
    projectId: 'ecommerce-abe3b',
    storageBucket: 'ecommerce-abe3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3OY6DE6v0ZwdnlhNm5qkNn3L5CQ7PeUk',
    appId: '1:1081926756389:ios:62e199d2bfe3a531d7b7cc',
    messagingSenderId: '1081926756389',
    projectId: 'ecommerce-abe3b',
    storageBucket: 'ecommerce-abe3b.appspot.com',
    iosBundleId: 'com.example.signeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3OY6DE6v0ZwdnlhNm5qkNn3L5CQ7PeUk',
    appId: '1:1081926756389:ios:62e199d2bfe3a531d7b7cc',
    messagingSenderId: '1081926756389',
    projectId: 'ecommerce-abe3b',
    storageBucket: 'ecommerce-abe3b.appspot.com',
    iosBundleId: 'com.example.signeup',
  );
}
